version = 0.1

# SAM Configuration for different environments

[default.global.parameters]
stack_name = "demo-bank-blue"
region = "eu-west-1"

[default.build.parameters]
cached = true
parallel = true

[default.package.parameters]
resolve_s3 = true

[default.local_start_api.parameters]
env_vars = "env.local.json"
port = 3000
warm_containers = "eager"

[default.deploy.parameters]
confirm_changeset = false
fail_on_empty_changeset = false
capabilities = "CAPABILITY_IAM"
region = "eu-west-1"
resolve_s3 = true

# Development Environment
[dev.deploy.parameters]
stack_name = "demo-bank-app-backend-dev"
s3_bucket = "demo-bank-app-deployments-dev"
region = "eu-west-1"
parameter_overrides = "Environment=dev DomainName=api.dev.demo-bank-app.labs.blue CertificateArn=arn:aws:acm:eu-west-1:118811228407:certificate/86fdd31e-dc7c-4eb2-8c81-0dbae7b9a3d1 HostedZoneId=Z08735701IVBXKWDBW8X3"
tags = "Environment=dev Project=demo-bank-app"
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
fail_on_empty_changeset = false

# Production Environment
[prod.deploy.parameters]
stack_name = "demo-bank-app-backend-prod"
s3_bucket = "demo-bank-app-deployments-prod"
region = "eu-west-1"
parameter_overrides = "Environment=prod DomainName=api.demo-bank-app.labs.blue CertificateArn=arn:aws:acm:eu-west-1:118811228407:certificate/86fdd31e-dc7c-4eb2-8c81-0dbae7b9a3d1 HostedZoneId=Z074376820QRVUQHNDT1H"
tags = "Environment=prod Project=demo-bank-app"
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
fail_on_empty_changeset = false
